#!/usr/bin/env bash

set -euxo pipefail

if [[ $# -gt 0 ]]; then
  echo "
  Usage: ${0##*/}
  Builds and installs superzent onto your system into ~/.local, making it available as ~/.local/bin/superzent.

  Before running this you should ensure you have all the build dependencies installed with `./script/linux`.
  "
  exit 1
fi
export SUPERZENT_CHANNEL=$(<crates/zed/RELEASE_CHANNEL)
export ZED_CHANNEL="$SUPERZENT_CHANNEL"
export SUPERZENT_UPDATE_EXPLANATION="You need to fetch and rebuild superzent in $(pwd)"
export ZED_UPDATE_EXPLANATION="$SUPERZENT_UPDATE_EXPLANATION"
script/bundle-linux

arch="$(uname -m)"
commit=$(git rev-parse HEAD | cut -c 1-7)
archive="superzent-linux-${arch}.tar.gz"
export SUPERZENT_BUNDLE_PATH="${CARGO_TARGET_DIR:-target}/release/${archive}"
export ZED_BUNDLE_PATH="$SUPERZENT_BUNDLE_PATH"
script/install.sh
