name: Deploy Cloudflare

on:
  push:
    branches:
      - main

jobs:
  deploy-cloudflare:
    name: Deploy Cloudflare
    if: github.repository_owner == 'currybab'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2f34d62369131b8448cec9ffbd4111f4c2 # v6.0.2
        with:
          clean: false

      - name: Deploy Release Worker
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy --config .cloudflare/release-assets/wrangler.toml

      - name: Preserve Wrangler logs
        uses: actions/upload-artifact@bbbca2ff186980d4b5400ce112fb0775aa163254 # v7.0.0
        if: always()
        with:
          name: wrangler_logs
          path: /home/runner/.config/.wrangler/logs/
